
services:
  app:
    image: local/reflex-app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
    volumes:
      - db-data:/app/data
      - ./OCDE/assets/uploads:/app/OCDE/assets/uploads
      - /home/admobge/obs-gen-reflex/OCDE/backend/:/app/OCDE/backend/
    restart: always

  webserver:
    environment:
      DOMAIN: ${DOMAIN:-localhost}
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: Caddy.Dockerfile
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - ./OCDE/assets/uploads:/srv/uploads
    restart: always
    depends_on:
      - app

volumes:
  db-data:
  caddy-data:
  caddy-config:
