"""empty message

Revision ID: 5380ba7f392f
Revises: e023699a81a3
Create Date: 2025-01-22 10:36:14.867823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5380ba7f392f'
down_revision: Union[str, None] = 'e023699a81a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigador')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigador',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(), nullable=False),
    sa.Column('magister', sa.VARCHAR(), nullable=False),
    sa.Column('doctorado', sa.VARCHAR(), nullable=False),
    sa.Column('programa', sa.VARCHAR(), nullable=False),
    sa.Column('linea', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
