"""empty message

Revision ID: e023699a81a3
Revises: 
Create Date: 2025-01-16 11:36:17.672906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e023699a81a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('magister', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doctorado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('programa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linea', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigador')
    # ### end Alembic commands ###
