name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd $HOME/obs-gen-reflex
          rm -f deploy.sh
          git pull origin main
          bash deploy.sh
